name = "THE LOTTODOME"
love_version = "11.5"
default_targets = ["win32", "win64", "macos", "lovejs"]
build_directory = "../dist"
love_files = [
    "+*",
    "-*/.*",
]
icon_file = "assets/icon.png"

[windows.exe_metadata]
FileDescription = "THE LOTTODOME"
FileVersion = "1.0"
CompanyName = "Keyslam & LeviR.star & SnugBoat"
LegalCopyright = "Copyright © 2024 Keyslam & LeviR.star & SnugBoat"
ProductName = "THE LOTTODOME"
ProductVersion = "1.0"
OriginalFilename = "THE_LOTTODOME.exe"

[win32]
shared_libraries = []
artifacts = "archive"

[win64]
shared_libraries = []
artifacts = "archive"

[macos.app_metadata]
CFBundleName = "THE LOTTODOME"
CFBundleIdentifier = "com.keyslam.THE_LOTTODOME"
NSHumanReadableCopyright = "Copyright © 2024 Keyslam & LeviR.star & SnugBoat"
CFBundleShortVersionString = "1.0"

[lovejs]
title = "THE LOTTODOME"
memory = "200000000"
